### ISSUE TITLE
list of client events

### ISSUE THREAD

**Issue by hlb-schmidt** [circuit/circuit-sdk#39]
where do we find the list of possible events for [addEventListener](https://circuitsandbox.net/sdk/classes/Client.html#method_addEventListener)?

**Comment by FalkW** [comment]
@hlb-schmidt check the "Events" tab on the Client-Constructor.

Events
accessTokenRenewed
basicSearchResults
callEnded
callIncoming
callNetworkQualityChanged
callRtpThresholdCleared
callRtpThresholdReached
callStatus
connectionStateChange
conversationArchived
conversationCreated
conversationFavorited
conversationReadItems
conversationUnarchived
conversationUnfavorited
conversationUpdated
conversationUserDataChanged
formSubmission
itemAdded
itemFlagged
itemUnflagged
itemUpdated
labelEdited
labelsAdded
labelsRemoved
loggedOnUserUpdated
mention
passwordChanged
reconnectFailed
renewAccessTokenFailed
renewSessionTokenFailed
searchStatus
sessionClosed
sessionExpiring
sessionTokenRenewed
systemMaintenance
typing
userPresenceChanged
userSettingsChanged
userUpdated
whiteboardBackground
whiteboardCleared
whiteboardConversionFailed
whiteboardElement
whiteboardEnabled
whiteboardOverlayToggled
whiteboardSync

**Comment by FalkW** [comment]
@rogeru as this question was answered we should close this issue.
