### ISSUE TITLE
Automation of Circuit mobile app calls with Unify's OS4K

### ISSUE THREAD

**Issue by hociungradu** [circuit/circuit-sdk#42]
Hi
I'm a member of the Solution test team for Circuit from Brasov, Romania. We are performing the Circuit tests with os4k and SBC (web browsers, desktop application, mobile clients). I'm interested in automation of the mobile Circuit calls trough os4k on both iOS and Android platforms (these tests we are performing now manually, which is a big time-consuming activity, especially for regression tests). 
On a quick read I found your work very interesting and I will study it more in details next weeks.
It might bring a great extra value to my work duties.
The guys from OSMO (Athens) integrated such kind of tests in an automated environment. Is there a way to perform also mobile tests with Circuit in automated environment - Jenkins, Appium, Android SDK or anything else? 
Can you help me designing and implementing such a solution? I'm learning automation from scratch now :)

Regards,
Radu Hociung
radu-mircea.hociung@atos.net

**Comment by rogeru** [comment]
Not relevant to Circuit JS SDK.
