### ISSUE TITLE
Scaling NodeJS Script for Multiple Users

### ISSUE THREAD

**Issue by SaravananOffl** [circuit/circuit-sdk#47]
I have written a simple bot using Node JS sdk, it is working fine for single user interaction. But when multiple users try to chat with the bot [  'itemAdded' Eventlistener is triggered ] at the same time this error raises.
```
Error:  Concurrent Client Requests: Encountered resource conflict while saving session data (see console for details) 
``` 

My bot is triggered when an item is added to the conversation, so when multiple users add an 
item at the same time how can the bot handle it ? any suggestions? 

(I tried using the PM2 [http://pm2.keymetrics.io/](url) to create multiple instances of the nodejs script, but when the users adds a item to the conversation all these multiple instances gets triggered, hence the user gets multiple replies)

You can find my code here:  https://repl.it/@SaravananG2/CircuitBot

**Comment by rogeru** [comment]
This looks like an issue with the postText API from AWS lex, at least thats the API throwing the error.

**Comment by ShriMLEngineer** [comment]
Was there any solution to this issue?
