### ISSUE TITLE
Error: Cannot find module './File'

### ISSUE THREAD

**Issue by Salzy** [circuit/circuit-sdk#53]
Hey,

when I install the latest version of circuit-sdk (1.2.7003) and run:
`const circuit = require('circuit-sdk');`

Then I get the following error:

> internal/modules/cjs/loader.js:638
>    throw err;
>   ^
>
>Error: Cannot find module './File'
>    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>    at Module.require (internal/modules/cjs/loader.js:692:17)
>    at require (internal/modules/cjs/helpers.js:25:18)
>    at Object.<anonymous> (C:\Admin\Projekte\Tests\node_modules\circuit-sdk\circuit-node.js:44:16)
>    at Module._compile (internal/modules/cjs/loader.js:778:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>    at Module.load (internal/modules/cjs/loader.js:653:32)
>    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by Salzy** [comment]
I just realized the latest version was just released 1h ago ...

**Comment by rogeru** [comment]
Yes, already updated github with that file. Pushing the new npm module  in a few min.

**Comment by rogeru** [comment]
Should be fine now. Please check.

**Comment by Salzy** [comment]
![image](https://user-images.githubusercontent.com/25642195/68130091-0daaad80-ff1b-11e9-82de-367c50113f01.png)

File.js is included now and works. Thanks :)
