### ISSUE TITLE
Newline when posting a form with multi-row INPUT

### ISSUE THREAD

**Issue by Salzy** [circuit/circuit-sdk#62]
When posting an interactive form containing a multi-row INPUT element, an empty row will be introduces before the input-element (see selected/blue area in screenshot). This happens when using both the SDK and the REST API. When I post a single row input, this will not happen!

![screenshot](https://user-images.githubusercontent.com/25642195/72256859-86f50980-360a-11ea-8183-bb81504766e3.png)

```
const Circuit = require('circuit-sdk');
const client = new Circuit.Client({
  client_id: 'TBD',
  client_secret: 'TBD',
  autoRenewToken: true,
  domain: 'circuitsandbox.net',
});

// Add conversation Id
const convId = 'TBD';

// Form data
const form = {
  content: 'Fill out the form to register a complaint',
  form: {
    id: 'myform1234',
    title: 'Complaint Form',
    controls: [
      {
        type: 'LABEL',
        text: 'Single-row INPUT:'
      },
      {
        type: 'INPUT',
        name: 'single',
        text: 'Single-row.',
      },
      {
        type: 'LABEL',
        text: 'Multi-row INPUT:'
      },
      {
        type: 'INPUT',
        name: 'multi',
        text: 'Multi-row introduces space above.',
        rows: 3,
      },
      {
        type: 'BUTTON',
        text: 'Send'
      }
    ],
  }
}

async function postForm() {
  const user = await client.logon();
  await client.addTextItem(convId, form);
}

postForm().then(console.log).catch(console.error);

```

**Comment by rogeru** [comment]
Thanks, yes I can confirm this is a bug. Will be fixed in the next version.

**Comment by Salzy** [comment]
Also I just realized, that this is an issue related to `size: 'large'`. When using `size: 'medium'`, the newline is not included.

**Comment by rogeru** [comment]
Yes, the calculated width (100% - 10px) is too wide for large text areas. Will be changed to 100% - 20px.

**Comment by Salzy** [comment]
Seams like its fixed now. Thanks.
