### ISSUE TITLE
Not able to use OAuth2 without redirect_uri

### ISSUE THREAD

**Issue by No-sudo-name** [circuit/circuit-sdk#68]
I have tried to use OAuth2 to login to Circuit and after granting access get told that no redirect is set.

I have used the following code like specified in the documentation:
```

const client = new Circuit.Client({
            domain: 'circuitsandbox.net',
            client_id: '78cafde2f6854ad5ad80a67c532687bc',
        });
client.logon()
            .then(user => console.log('Logged on as ' + user.displayName))
```

**Comment by rogeru** [comment]
You should get your own client_id instead of using the one shown on the github page. Follow the instructions at https://circuit.github.io/ to register your own app on the sandbox. As part of that registration you need to specify your redirect url, which is the url your website is hosted.

**Comment by No-sudo-name** [comment]
Thank you very much.
